AgentApp/Models/ErrorViewModel.cs
using System;

namespace AgentApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgentApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AgentApp.BusinessOperation.Interfaces;
using AgentApp.BusinessOperation.Operations;
using AgentApp.DataAccess.Entity;
using AgentApp.Helper;
using AgentApp.CustomFilters;

namespace AgentApp.Controllers
{
    public class AccountController : Controller
    {
        private readonly IBOUser _bOUser;
        public readonly ISessionManager _sesssionManager;

        public AccountController(IBOUser bOUser,  ISessionManager sessionManager)
        {
            _bOUser = bOUser;
            _sesssionManager = sessionManager;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(TblUser tblUser)
        {
            TblUser _tblData = await _bOUser.Authenticate(tblUser);
            if (_tblData == null)
            {
                ViewBag.UserError = "Email or password is not correct";
            }
            else
            {
                _sesssionManager.SiteUser = _tblData;
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public IActionResult Logout()
        {
            _sesssionManager.clearSession();
            return RedirectToAction("Login", "Account");
        }

        public IActionResult ErrorRequest()
        {
            return View();
        }

        //public IActionResult _void()
        //{
        //    return JsonResult
        //}


    }
}

AgentApp/Controllers/AgentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AgentApp.DataAccess.Entity;
using AgentApp.BusinessOperation.Interfaces;
using AgentApp.CustomFilters;
using System.Web.Http.Description;
using AgentApp.DTO.CustomDTO;
namespace AgentApp.Controllers
{
    [AuthRequest]

    public class AgentController : Controller
    {
        public readonly IBOAgent _bOAgent;
        public AgentController(IBOAgent bOAgent)
        {
            _bOAgent = bOAgent;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult LoadAgentData()
        {
            try
            {
                var jsonData = _bOAgent.LoadAllAgents(Request);
                return Ok(jsonData);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public IActionResult AddAgent(string Inkey)
        {
            ViewBag.AgentId = string.IsNullOrEmpty(Inkey) ? string.Empty : Inkey;
            return View(_bOAgent.GetData(Inkey));
        }

        [HttpPost]
        //[ResponseType(typeof(AgentRecordDTO))]
        public async Task<JsonResult> AddAgent(AgentRecordDTO agentRecord)
        {
            dynamic data = string.Empty;
            if (ModelState.IsValid)
                data = await _bOAgent.AddAgent(agentRecord);
            return Json(data);
        }
        [HttpPost]
        //[ResponseType(typeof(AgentRecordDTO))]
        public async Task<JsonResult> DeleteAgent(AgentRecordDTO agentRecord)
        {
            dynamic data = string.Empty;
            await _bOAgent.DeleteAgentRecord(agentRecord);
            return Json(data);
        }
        [HttpPost]
        public JsonResult LoadAgentLineGraph()
        {
            dynamic data = _bOAgent.LoadLineGraph();
            return Json(data);
        }
    }
}

AgentApp/Controllers/BaseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AgentApp.Common;
using System.Security.Claims;
using AgentApp.DataAccess.Entity;
using Newtonsoft.Json;
using AgentApp.Helper;

namespace AgentApp.Controllers
{
    public struct Role
    {
        public const string Admin = "Admin";
        public const string Guest = "Guest";
    }
    public class BaseController : Controller
    {
        public readonly SessionManager _sesssionManager;
        public BaseController(SessionManager sessionManager)
        {
            _sesssionManager = sessionManager;
        }
        public IActionResult Index()
        {
            return View();
        }
       
    }
}

AgentApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AgentApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AgentApp.BusinessOperation.Interfaces;
using AgentApp.DataAccess.Entity;
using AgentApp.CustomFilters;

namespace AgentApp.Controllers
{
    [AuthRequest]

    public class HomeController : Controller
    {
        private readonly IBOStudent _bOStudent;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IBOStudent bOStudent)
        {
            _logger = logger;
            _bOStudent = bOStudent;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public async Task<IActionResult> AddStudent()
        {
            TblRawDatum tblRawDatum = new TblRawDatum
            {
                FirstName = "Test",
                Email = "Test@gmail.com",
                LastName = "Test 2"
            };
            if (ModelState.IsValid)
                await _bOStudent.AddTblPatient(tblRawDatum);
            return View();
        }
    }
}

AgentApp/Views/Agent/AddAgent.cshtml
@model AgentApp.DTO.CustomDTO.AgentRecordDTO;
@{
    ViewData["Title"] = "AddAgent";
}

<style>
    input.error, textarea.error {
        border: 1px dashed red;
        font-weight: 300;
        color: red;
    }

    label.error {
        color: red;
        font-size: 1rem;
        display: block;
        margin-top: 5px;
    }

    .required {
        color: red;
    }
</style>

@* Header Block *@
<div class="block-header">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Add New Agent</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item">Agents</li>
                <li class="breadcrumb-item active">Add New Agent</li>
            </ul>
        </div>
    </div>
</div>




@* Page Content *@
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                @*<h2>Agent Form</h2>*@
            </div>
            <div class="body">
                <form id="addAgentForm">
                    <input type="hidden" value="@ViewBag.AgentId" id="hfEncryptAgentId" />
                    <div class="row">
                        @* ------------------------------------Agent Name------------------------------------ *@
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Agent Name <span class="required">*</span></label>
                                <input type="text" id="AgentName" name="AgentName" placeholder="Agent Name" class="form-control" value="@Model.AgentName">
                            </div>
                        </div>

                        @* ------------------------------------WorkingArea------------------------------------ *@
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Working Area <span class="required">*</span></label>
                                @{
                                    List<SelectListItem> listItems = new List<SelectListItem>();
                                    listItems.Add(new SelectListItem { Text = "-Select Working Area-", Value = "0", Selected = (Model.WorkingArea == "Select Working Area" ? true : false) });
                                    listItems.Add(new SelectListItem { Text = "School", Value = "School", Selected = (Model.WorkingArea == "School" ? true : false) });
                                    listItems.Add(new SelectListItem { Text = "University", Value = "University", Selected = (Model.WorkingArea == "University" ? true : false) });
                                    listItems.Add(new SelectListItem { Text = "Office", Value = "Office", Selected = (Model.WorkingArea == "Office" ? true : false) });
                                    listItems.Add(new SelectListItem { Text = "Hospital", Value = "Hospital", Selected = (Model.WorkingArea == "Hospital" ? true : false) });
                                    <select class="form-control" asp-for="WorkingArea" name="WorkingArea" asp-items="listItems"></select>
                                }
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        @* ------------------------------------Commission------------------------------------ *@
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Commission <span class="required">*</span></label>
                                <input type="text" id="Commission" name="Commission" placeholder="Commission" class="form-control" value="@Model.Commission">
                            </div>
                        </div>
                        @* ------------------------------------Phone No------------------------------------ *@
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Phone No</label>
                                <input type="text" id="PhoneNo" name="PhoneNo" placeholder="ex: (999) 999-9999" class="form-control" value="@Model.PhoneNo">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        @* ------------------------------------Country------------------------------------ *@
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Country</label>
                                <input type="text" id="Country" name="Country" placeholder="Country" class="form-control" value="@Model.Country">
                            </div>
                        </div>
                    </div>
                    <br />
                    <button type="submit" id="btnSaveAgent" class="btn btn-success"><i class='fa fa-save'></i> <span>@((string.IsNullOrEmpty(ViewBag.AgentId)) ? "Save" : "Update")</span> </button>
                    <button type="button" id="showButtonLoading" style="display:none;" class="btn btn-primary" disabled="disabled"><i class="fa fa-spinner fa-spin"></i> <span>Loading...</span></button>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/assets/Scripts/AddNewAgent.js"></script>
    <script src="../assets/vendor/jquery-inputmask/jquery.inputmask.bundle.js"></script> <!-- Input Mask Plugin Js -->
}

AgentApp/Views/Agent/Index.cshtml
@{
    ViewData["Title"] = "Agent List";
}
@section CSS
{
    <link rel="stylesheet" href="../assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="../assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet" href="../assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="../assets/vendor/sweetalert/sweetalert.css" />
    <style>
        table.dataTable {
            border-collapse: collapse !important;
        }
    </style>
}

@* Header Block *@
<div class="block-header">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2><a asp-controller="Home" asp-action="Index" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Add New Agent</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item">Agents</li>
                <li class="breadcrumb-item active">All Agents</li>
            </ul>
        </div>
    </div>
</div>

@* Page Content *@
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card" style="width:auto">
            <div class="header">
                <a asp-controller="Agent" asp-action="AddAgent" class="btn btn-success"><i class='fa fa-plus'></i> <span>Add New Agents</span></a>
            </div>
            <div class="body">


                @*<table class="table table-hover dataTable table-custom" id="tblLoadAllAgent">*@

                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="tblLoadAllAgent" style="white-space: nowrap;">
                    <thead>
                        <tr role="row" class="filter">
                            <td></td>
                            <td>
                                <input type="text" class="form-control" id="AgentName" />
                            </td>
                            <td>
                                <input type="text" class="form-control" id="WokingArea" />
                            </td>
                            <td>
                                <input type="text" class="form-control" id="Commission" />
                            </td>
                            <td>
                                <input type="text" class="form-control" id="PhoneNo" />
                            </td>
                            <td>
                                <input type="text" class="form-control" id="Country" />
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>Agent Id</th>
                            <th>Agent Name</th>
                            <th>Woking Area</th>
                            <th>Commission</th>
                            <th>Phone No</th>
                            <th>Country</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


@* Scripts Block *@
@section Scripts{
     <script src="~/assets/Scripts/LoadAllAgents.js"></script>
    <script src="../assets/bundles/datatablescripts.bundle.js"></script>
    <script src="../assets/vendor/jquery-datatable/buttons/dataTables.buttons.min.js"></script>
    <script src="../assets/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
    <script src="../assets/vendor/jquery-datatable/buttons/buttons.colVis.min.js"></script>
    <script src="../assets/vendor/jquery-datatable/buttons/buttons.html5.min.js"></script>
    <script src="../assets/vendor/jquery-datatable/buttons/buttons.print.min.js"></script>
    <script src="../assets/vendor/sweetalert/sweetalert.min.js"></script> <!-- SweetAlert Plugin Js -->
    <script src="../assets/js/pages/tables/jquery-datatable.js"></script>

    <script>
        $(document).ready(function () {
            $('.star').on('click', function () {
                $(this).toggleClass('star-checked');
            });

            $('.ckbox label').on('click', function () {
                $(this).parents('tr').toggleClass('selected');
            });

            $('.btn-filter').on('click', function () {
                var $target = $(this).data('target');
                if ($target != 'all') {
                    $('.table tr').css('display', 'none');
                    $('.table tr[data-status="' + $target + '"]').fadeIn('slow');
                } else {
                    $('.table tr').css('display', 'none').fadeIn('slow');
                }
            });
        });
    </script>

}

AgentApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<div class="block-header">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Dashboard</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ul>
        </div>
        @*<div class="col-lg-6 col-md-4 col-sm-12 text-right">
            <div class="bh_chart hidden-xs">
                <div class="float-left m-r-15">
                    <small>Visitors</small>
                    <h6 class="mb-0 mt-1"><i class="icon-user"></i> 1,784</h6>
                </div>
                <span class="bh_visitors float-right">2,5,1,8,3,6,7,5</span>
            </div>
            <div class="bh_chart hidden-sm">
                <div class="float-left m-r-15">
                    <small>Visits</small>
                    <h6 class="mb-0 mt-1"><i class="icon-globe"></i> 325</h6>
                </div>
                <span class="bh_visits float-right">10,8,9,3,5,8,5</span>
            </div>
            <div class="bh_chart hidden-sm">
                <div class="float-left m-r-15">
                    <small>Chats</small>
                    <h6 class="mb-0 mt-1"><i class="icon-bubbles"></i> 13</h6>
                </div>
                <span class="bh_chats float-right">1,8,5,6,2,4,3,2</span>
            </div>
        </div>*@
    </div>
</div>

<div class="row clearfix">
    <div class="col-lg-3 col-md-12">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-6">
                <div class="card top_counter">
                    <div class="body">
                        <div id="top_counter1" class="carousel vert slide" data-ride="carousel" data-interval="2500">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="icon"><i class="fa fa-user"></i> </div>
                                    <div class="content">
                                        <div class="text">Total Agents</div>
                                        <h5 class="number">215</h5>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="icon"><i class="fa fa-user"></i> </div>
                                    <div class="content">
                                        <div class="text">New Agent</div>
                                        <h5 class="number">21</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div id="top_counter2" class="carousel vert slide" data-ride="carousel" data-interval="2100">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="icon"><i class="fa fa-user-md"></i> </div>
                                    <div class="content">
                                        <div class="text">Operations</div>
                                        <h5 class="number">06</h5>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-6">
                <div class="card top_counter">
                    <div class="body">
                        <div id="top_counter3" class="carousel vert slide" data-ride="carousel" data-interval="2300">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="icon"><i class="fa fa-eye"></i> </div>
                                    <div class="content">
                                        <div class="text">Total Old Sales</div>
                                        <h5 class="number">10K</h5>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="icon"><i class="fa fa-eye"></i> </div>
                                    <div class="content">
                                        <div class="text">Todal Sales</div>
                                        <h5 class="number">142</h5>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="icon"><i class="fa fa-eye"></i> </div>
                                    <div class="content">
                                        <div class="text">Total Visitors</div>
                                        <h5 class="number">2,087</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="icon"><i class="fa fa-university"></i> </div>
                        <div class="content">
                            <div class="text">Revenue</div>
                            <h5 class="number">$18,925</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="card top_counter">
                    <div class="body">
                        <div class="icon"><i class="fa fa-thumbs-o-up"></i> </div>
                        <div class="content">
                            <div class="text">Happy Clients</div>
                            <h5 class="number">528</h5>
                        </div>
                        <hr>
                        <div class="icon"><i class="fa fa-smile-o"></i> </div>
                        <div class="content">
                            <div class="text">Smiley Faces</div>
                            <h5 class="number">2,528</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-md-12">
        <div class="card">
            <div class="header">
                <h2>Total Agents</h2>
                @*<ul class="header-dropdown">
                    <li><a class="tab_btn" href="javascript:void(0);" title="Weekly">W</a></li>
                    <li><a class="tab_btn" href="javascript:void(0);" title="Monthly">M</a></li>
                    <li><a class="tab_btn active" href="javascript:void(0);" title="Yearly">Y</a></li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another Action</a></li>
                            <li><a href="javascript:void(0);">Something else</a></li>
                        </ul>
                    </li>
                </ul>*@
            </div>
            <div class="body">
                <div class="row clearfix">
                    <div class="col-md-4">
                        <div class="body bg-success text-light">
                            <h4><i class="icon-wallet"></i> 7,12,326$</h4>
                            <span>Total Agent Income</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="body bg-warning text-light">
                            <h4><i class="icon-wallet"></i> 25,965$</h4>
                            <span>Total Reward Income</span>
                        </div> 
                    </div>
                    <div class="col-md-4">
                        <div class="body bg-danger text-light">
                            <h4><i class="icon-wallet"></i> 14,965$</h4>
                            <span>Total Agent Expenses</span>
                        </div>
                    </div>
                </div>
                <div id="total_revenue" class="ct-chart m-t-20"></div>
            </div>
        </div>
    </div>
</div>

AgentApp/Views/Shared/_ViewSideMenuPartial.cshtml
<div id="left-sidebar" class="sidebar">
    <div class="sidebar-scroll">
        <div class="user-account">
            <img src="../assets/images/user.png" class="rounded-circle user-photo" alt="User Profile Picture">
            <div class="dropdown">
                <span>Welcome,</span>
                <a href="javascript:void(0);" class="dropdown-toggle user-name" data-toggle="dropdown"><strong>@sessionManager.SiteUser.Email</strong></a>
                <ul class="dropdown-menu dropdown-menu-right account">
                    @*<li><a href="doctor-profile.html"><i class="icon-user"></i>My Profile</a></li>
                    <li><a href="app-inbox.html"><i class="icon-envelope-open"></i>Messages</a></li>
                    <li><a href="javascript:void(0);"><i class="icon-settings"></i>Settings</a></li>*@
                    @*<li class="divider"></li>*@
                    <li><a asp-controller="Account" asp-action="Logout"><i class="icon-power"></i>Logout</a></li>
                </ul>
            </div>
            <hr>
        </div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#menu">Menu</a></li>
           @* <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#setting"><i class="icon-settings"></i></a></li>*@
        </ul>

        <!-- Tab panes -->
        <div class="tab-content p-l-0 p-r-0">
            <div class="tab-pane active" id="menu">
                <nav class="sidebar-nav">
                    @*@await Component.InvokeAsync("Menu");*@
                    <ul class="main-menu metismenu">
                        <li><a asp-controller="Home" asp-action="Index"><i class="icon-home"></i><span>Dashboard</span></a></li>
                            <li>
                                <a href="javascript:void(0);" class="has-arrow"><i class="icon-user-follow"></i><span>Agent Record</span> </a>
                                <ul>
                                    <li> <a asp-controller="Agent" asp-action="Index">Agent List</a></li>
                                    <li> <a asp-controller="Agent" asp-action="AddAgent">Agent Form</a></li>
                                </ul>
                            </li>
                    </ul>
                </nav>
            </div>
            
            
            <div class="tab-pane p-l-15 p-r-15" id="setting">
                <h6>Choose Skin</h6>
                <ul class="choose-skin list-unstyled">
                    <li data-theme="purple">
                        <div class="purple"></div>
                        <span>Purple</span>
                    </li>
                    <li data-theme="blue">
                        <div class="blue"></div>
                        <span>Blue</span>
                    </li>
                    <li data-theme="cyan" class="active">
                        <div class="cyan"></div>
                        <span>Cyan</span>
                    </li>
                    <li data-theme="green">
                        <div class="green"></div>
                        <span>Green</span>
                    </li>
                    <li data-theme="orange">
                        <div class="orange"></div>
                        <span>Orange</span>
                    </li>
                    <li data-theme="blush">
                        <div class="blush"></div>
                        <span>Blush</span>
                    </li>
                </ul>
                <hr>
                <h6>General Settings</h6>
                <ul class="setting-list list-unstyled">
                    <li>
                        <label class="fancy-checkbox">
                            <input type="checkbox" name="checkbox">
                            <span>Report Panel Usag</span>
                        </label>
                    </li>
                    <li>
                        <label class="fancy-checkbox">
                            <input type="checkbox" name="checkbox">
                            <span>Email Redirect</span>
                        </label>
                    </li>
                    <li>
                        <label class="fancy-checkbox">
                            <input type="checkbox" name="checkbox" checked>
                            <span>Notifications</span>
                        </label>
                    </li>
                    <li>
                        <label class="fancy-checkbox">
                            <input type="checkbox" name="checkbox" checked>
                            <span>Auto Updates</span>
                        </label>
                    </li>
                    <li>
                        <label class="fancy-checkbox">
                            <input type="checkbox" name="checkbox">
                            <span>Offline</span>
                        </label>
                    </li>
                    <li>
                        <label class="fancy-checkbox">
                            <input type="checkbox" name="checkbox" checked>
                            <span>Location Permission</span>
                        </label>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>